name: Run tests after commit

on: [push]

jobs:
  run-tests:
    name: Run tests after commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest