name: Run tests after commit

on: [push]

jobs:
  run-tests:
    name: Run tests after commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "--version"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Run formatting checks
        run: ruff check
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest